package com.pocketledger.ui.components

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.pocketledger.R

/**
 * The app's icon set.
 *
 * These used to be drawn procedurally with `DrawScope` in this file. The geometry now
 * lives in `res/drawable/ic_ledger_*.xml`, generated by `icons/generate_icons.py` from the
 * same source that produces the exported SVG set -- so the icons in the app and the icons
 * in `icons/` cannot drift apart, and a shape can be edited in one place.
 *
 * The reason for the move was the two brand marks (微信支付 / 支付宝): a logo cannot be
 * hand-written as lines and arcs, so it had to be traced from the real artwork, and a
 * traced path belongs in a vector resource rather than in a Kotlin string. Once two icons
 * lived as path data, having the other twenty-nine as drawing code meant two sources for
 * one set.
 *
 * Everything is monochrome by design: the app tints at runtime, because the same glyph has
 * to render in a category's colour, the theme's primary, or a disabled grey.
 */
enum class LedgerIcon {
    // Navigation
    LIST,
    CHART,
    /** A month grid, for the header button that switches to calendar view. */
    CALENDAR,
    WALLET,
    PERSON,
    PLUS,
    SETTINGS,
    CHEVRON_RIGHT,
    /** Three dots: opens the full category list from the entry grid. */
    ELLIPSIS,
    /** A magnifier: opens the search screen. */
    SEARCH,

    // Expense 大类
    FOOD,
    TRANSPORT,
    SHOPPING,
    HOME,
    COMMS,
    STUDY,
    CAMPUS,
    FUN,
    MEDICAL,
    GIFT,
    FINANCE,
    WORK,
    PET,
    OTHER,

    // Income and accounts
    INCOME,
    CASH,
    CARD,
    BANK,
    /** 支付宝: the brand's 支 mark, traced from the official artwork. */
    ALIPAY,
    /** 微信支付: the brand's speech bubble, traced from the official artwork. */
    WECHAT,

    /** Used for custom categories that carry no curated key. */
    TAG,
    ;

    companion object {
        /**
         * Maps a stored `iconKey` to a glyph.
         *
         * Unknown or missing keys fall back to [TAG] rather than [OTHER] so a custom
         * category looks deliberate rather than mis-filed under 其他.
         */
        fun forKey(key: String?): LedgerIcon = when (key) {
            "food" -> FOOD
            "transport" -> TRANSPORT
            "shopping" -> SHOPPING
            "home" -> HOME
            "comms" -> COMMS
            "study" -> STUDY
            "campus" -> CAMPUS
            "fun" -> FUN
            "medical" -> MEDICAL
            "gift" -> GIFT
            "finance" -> FINANCE
            "work" -> WORK
            "pet" -> PET
            "other" -> OTHER
            "calendar" -> CALENDAR
            "income" -> INCOME
            "cash" -> CASH
            "card", "prepaid" -> CARD
            "bank" -> BANK
            "alipay" -> ALIPAY
            "wechat" -> WECHAT
            "wallet" -> WALLET
            else -> TAG
        }
    }
}

/**
 * The drawable behind one icon.
 *
 * A `when` **expression** over the enum rather than a map: adding a constant to [LedgerIcon]
 * then fails the build until it is given a file, which is the check that used to be a
 * count-a-test-against-the-directory script.
 */
@DrawableRes
private fun LedgerIcon.drawable(): Int = when (this) {
    LedgerIcon.LIST -> R.drawable.ic_ledger_list
    LedgerIcon.CHART -> R.drawable.ic_ledger_chart
    LedgerIcon.CALENDAR -> R.drawable.ic_ledger_calendar
    LedgerIcon.WALLET -> R.drawable.ic_ledger_wallet
    LedgerIcon.PERSON -> R.drawable.ic_ledger_person
    LedgerIcon.PLUS -> R.drawable.ic_ledger_plus
    LedgerIcon.SETTINGS -> R.drawable.ic_ledger_settings
    LedgerIcon.CHEVRON_RIGHT -> R.drawable.ic_ledger_chevron_right
    LedgerIcon.ELLIPSIS -> R.drawable.ic_ledger_ellipsis
    LedgerIcon.SEARCH -> R.drawable.ic_ledger_search
    LedgerIcon.FOOD -> R.drawable.ic_ledger_food
    LedgerIcon.TRANSPORT -> R.drawable.ic_ledger_transport
    LedgerIcon.SHOPPING -> R.drawable.ic_ledger_shopping
    LedgerIcon.HOME -> R.drawable.ic_ledger_home
    LedgerIcon.COMMS -> R.drawable.ic_ledger_comms
    LedgerIcon.STUDY -> R.drawable.ic_ledger_study
    LedgerIcon.CAMPUS -> R.drawable.ic_ledger_campus
    LedgerIcon.FUN -> R.drawable.ic_ledger_fun
    LedgerIcon.MEDICAL -> R.drawable.ic_ledger_medical
    LedgerIcon.GIFT -> R.drawable.ic_ledger_gift
    LedgerIcon.FINANCE -> R.drawable.ic_ledger_finance
    LedgerIcon.WORK -> R.drawable.ic_ledger_work
    LedgerIcon.PET -> R.drawable.ic_ledger_pet
    LedgerIcon.OTHER -> R.drawable.ic_ledger_other
    LedgerIcon.INCOME -> R.drawable.ic_ledger_income
    LedgerIcon.CASH -> R.drawable.ic_ledger_cash
    LedgerIcon.CARD -> R.drawable.ic_ledger_card
    LedgerIcon.BANK -> R.drawable.ic_ledger_bank
    LedgerIcon.ALIPAY -> R.drawable.ic_ledger_alipay
    LedgerIcon.WECHAT -> R.drawable.ic_ledger_wechat
    LedgerIcon.TAG -> R.drawable.ic_ledger_tag
}

/** One tinted glyph at [size]; the single entry point every screen uses. */
@Composable
fun LedgerIconView(
    icon: LedgerIcon,
    tint: Color,
    modifier: Modifier = Modifier,
    size: Dp = 24.dp,
) {
    Icon(
        painter = painterResource(icon.drawable()),
        contentDescription = null,
        tint = tint,
        modifier = modifier.size(size),
    )
}
