package com.pocketledger.data

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v3 -> v4.
 *
 * GENERATED by `.toolchain/tools/generate_migration.py` from the exported schemas.
 * Do not edit by hand: change the entities, rebuild so Room re-exports
 * `app/schemas/`, then re-run the generator with `--write`.
 *
 * The generator also proves the result: it replays the v3 schema plus these
 * statements in a real SQLite database and compares the outcome against what
 * v4 expects. That check exists because Room only validates a migration when
 * the database is opened on a device, and this project has no device.
 */
val MIGRATION_3_4: Migration = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE `account` ADD COLUMN `balanceAsOfMillis` INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE `txn` ADD COLUMN `timeMode` TEXT NOT NULL DEFAULT 'AUTO'")
    }
}
