package com.pocketledger.data

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v1 -> v2.
 *
 * GENERATED by `.toolchain/tools/generate_migration.py` from the exported schemas.
 * Do not edit by hand: change the entities, rebuild so Room re-exports
 * `app/schemas/`, then re-run the generator with `--write`.
 *
 * The generator also proves the result: it replays the v1 schema plus these
 * statements in a real SQLite database and compares the outcome against what
 * v2 expects. That check exists because Room only validates a migration when
 * the database is opened on a device, and this project has no device.
 */
val MIGRATION_1_2: Migration = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("CREATE TABLE IF NOT EXISTS `ledger` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NOT NULL, `type` TEXT NOT NULL, `iconKey` TEXT NOT NULL, `colorArgb` INTEGER NOT NULL, `sortOrder` INTEGER NOT NULL, `isArchived` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL, `deletedAt` INTEGER)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_ledger_isArchived` ON `ledger` (`isArchived`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_ledger_sortOrder` ON `ledger` (`sortOrder`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `installment_plan` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `ledgerId` INTEGER NOT NULL DEFAULT 1, `name` TEXT NOT NULL, `kind` TEXT NOT NULL, `totalAmountCents` INTEGER NOT NULL, `periodCount` INTEGER NOT NULL, `perPeriodCents` INTEGER NOT NULL, `repayDay` INTEGER NOT NULL, `startDateKey` TEXT NOT NULL, `accountId` INTEGER, `categoryId` INTEGER, `note` TEXT, `isActive` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_installment_plan_ledgerId` ON `installment_plan` (`ledgerId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_installment_plan_isActive` ON `installment_plan` (`isActive`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_installment_plan_accountId` ON `installment_plan` (`accountId`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `installment_period` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `planId` INTEGER NOT NULL, `periodIndex` INTEGER NOT NULL, `dueDateKey` TEXT NOT NULL, `amountCents` INTEGER NOT NULL, `txnId` INTEGER, `generatedAt` INTEGER, FOREIGN KEY(`planId`) REFERENCES `installment_plan`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_installment_period_planId_periodIndex` ON `installment_period` (`planId`, `periodIndex`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_installment_period_txnId` ON `installment_period` (`txnId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_installment_period_dueDateKey` ON `installment_period` (`dueDateKey`)")
        db.execSQL("ALTER TABLE `account` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("ALTER TABLE `account` ADD COLUMN `isHidden` INTEGER NOT NULL DEFAULT 0")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_account_ledgerId` ON `account` (`ledgerId`)")
        db.execSQL("ALTER TABLE `category` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE TABLE IF NOT EXISTS `category_new` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `ledgerId` INTEGER NOT NULL DEFAULT 1, `name` TEXT NOT NULL, `kind` TEXT NOT NULL, `parentId` INTEGER, `iconKey` TEXT NOT NULL, `colorArgb` INTEGER NOT NULL, `sortOrder` INTEGER NOT NULL, `isSystem` INTEGER NOT NULL, `isArchived` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL, `deletedAt` INTEGER)")
        db.execSQL("INSERT INTO `category_new` (`id`, `ledgerId`, `name`, `kind`, `parentId`, `iconKey`, `colorArgb`, `sortOrder`, `isSystem`, `isArchived`, `createdAt`, `updatedAt`, `deletedAt`) SELECT `id`, `ledgerId`, `name`, `kind`, `parentId`, `iconKey`, `colorArgb`, `sortOrder`, `isSystem`, `isArchived`, `createdAt`, `updatedAt`, `deletedAt` FROM `category`")
        db.execSQL("DROP TABLE `category`")
        db.execSQL("ALTER TABLE `category_new` RENAME TO `category`")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_category_ledgerId` ON `category` (`ledgerId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_category_parentId` ON `category` (`parentId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_category_ledgerId_kind_parentId_sortOrder` ON `category` (`ledgerId`, `kind`, `parentId`, `sortOrder`)")
        db.execSQL("ALTER TABLE `txn` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("ALTER TABLE `txn` ADD COLUMN `planId` INTEGER")
        db.execSQL("ALTER TABLE `txn` ADD COLUMN `planPeriodIndex` INTEGER")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_txn_ledgerId` ON `txn` (`ledgerId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_txn_planId_planPeriodIndex` ON `txn` (`planId`, `planPeriodIndex`)")
        db.execSQL("ALTER TABLE `tag` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_tag_ledgerId_name` ON `tag` (`ledgerId`, `name`)")
        db.execSQL("DROP INDEX IF EXISTS `index_tag_name`")
        db.execSQL("ALTER TABLE `budget` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_budget_ledgerId` ON `budget` (`ledgerId`)")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_budget_ledgerId_periodType_periodKey_scope_categoryId` ON `budget` (`ledgerId`, `periodType`, `periodKey`, `scope`, `categoryId`)")
        db.execSQL("DROP INDEX IF EXISTS `index_budget_periodType_periodKey_scope_categoryId`")
        db.execSQL("ALTER TABLE `allowance` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_allowance_ledgerId_periodKey` ON `allowance` (`ledgerId`, `periodKey`)")
        db.execSQL("DROP INDEX IF EXISTS `index_allowance_periodKey`")
        db.execSQL("ALTER TABLE `term` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_term_ledgerId` ON `term` (`ledgerId`)")
        db.execSQL("ALTER TABLE `wish` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_wish_ledgerId` ON `wish` (`ledgerId`)")
        db.execSQL("ALTER TABLE `saving_goal` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_saving_goal_ledgerId` ON `saving_goal` (`ledgerId`)")
        db.execSQL("ALTER TABLE `template` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_template_ledgerId` ON `template` (`ledgerId`)")
        db.execSQL("ALTER TABLE `import_rule` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_import_rule_ledgerId_keyword` ON `import_rule` (`ledgerId`, `keyword`)")
        db.execSQL("DROP INDEX IF EXISTS `index_import_rule_keyword`")
        db.execSQL("ALTER TABLE `import_batch` ADD COLUMN `ledgerId` INTEGER NOT NULL DEFAULT 1")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_import_batch_ledgerId` ON `import_batch` (`ledgerId`)")
    }
}
