package com.pocketledger.data

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v2 -> v3.
 *
 * GENERATED by `.toolchain/tools/generate_migration.py` from the exported schemas.
 * Do not edit by hand: change the entities, rebuild so Room re-exports
 * `app/schemas/`, then re-run the generator with `--write`.
 *
 * The generator also proves the result: it replays the v2 schema plus these
 * statements in a real SQLite database and compares the outcome against what
 * v3 expects. That check exists because Room only validates a migration when
 * the database is opened on a device, and this project has no device.
 */
val MIGRATION_2_3: Migration = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE `installment_plan` ADD COLUMN `feeCents` INTEGER")
    }
}
